theme: jekyll-theme-cayman
title: My Project Name
description: A GitHub Pages site similar to Project Aria Tools

# plugins:
#   - jekyll-toc
#   - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

toc:
  min_level: 2
  max_level: 6
  ordered_list: true