# theme: jekyll-theme-cayman
theme: null
title: Home
description: A GitHub Pages site similar to Project Aria Tools

baseurl: "/tars_project/docs" 

url: "https://xrbio.github.io" 

markdown: kramdown
kramdown:
  input: GFM

include:
  - styles.css